apiVersion: apps/v1
kind: Deployment
metadata:
  name: dick-msa-ordering-depl
  namespace: dickjunseo-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dick-msa-ordering
  template:
    metadata:
      labels:
        app: dick-msa-ordering
    spec:
      containers:
      - name: dick-msa-ordering
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/dick-msa-order:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dick-app-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: dick-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: dick-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: dick-app-secrets
              key: AWS_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: dick-msa-ordering-service
  namespace: dickjunseo-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dick-msa-ordering